runtime: go111

service: default
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.80
  target_throughput_utilization: 0.80
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 1
  max_concurrent_requests: 10
  min_pending_latency: automatic
  max_pending_latency: automatic